name: daily-twitter-bot-name

on:
  workflow_dispatch:
  schedule:
    - cron: "00 00 * * *"

jobs:
  Rename:
    runs-on: ubuntu-latest
    env:
      API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
      API_KEY: ${{ secrets.API_KEY }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.19.x"
      - name: Go build
        run: go build -o twitter-bot -v ./...
      - name: Run app
        run: ./twitter-bot
