name: daily-twitter-bot-name

on:
  workflow_dispatch:
  schedule:
    - cron: "00 00 * * *"

jobs:
  Rename:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.x"
      - name: Set variables
        run: |
          echo "API_KEY_SECRET=${{ secrets.API_KEY_SECRET }}" >> "$GITHUB_ENV"
          echo "API_KEY=${{ secrets.API_KEY }}" >> "$GITHUB_ENV"
          echo "ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }}" >> "$GITHUB_ENV"
          echo "ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}" >> "$GITHUB_ENV"
      - name: Run bot rename
        run: make build-github
